### ISSUE TITLE
Skill response was marked as failure

### ISSUE THREAD

**Issue by BopItFreak** [ndg63276/alexa-youtube#144]
I'm getting this on the alexa logs....

![image](https://user-images.githubusercontent.com/41522720/73321349-2ff95200-4210-11ea-970c-954f71cb9cfa.png)

how do I fix this? It works like half the time for some reason. This only started happening very recently

Edit: Here are some logs printed in AWS cloudwatch:
```
/var/task/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning

01:52:01
warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

01:52:01
START RequestId: 017cc567-68e7-4dc5-a16a-3ad0faacb665 Version: $LATEST

01:52:01
[INFO] 2020-01-29T01:52:01.565Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 {u'session': {u'new': True, u'sessionId': u'amzn1.echo-api.session.5f51ee91-3583-46e3-92be-6416e17262b5', u'user': {u'userId': u'amzn1.ask.account.redacted

01:52:01
[INFO] 2020-01-29T01:52:01.565Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Looking for: Gangnam style by Psy

01:52:01
[INFO] 2020-01-29T01:52:01.565Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 checking for faves

01:52:01
[INFO] 2020-01-29T01:52:01.663Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 No Youtube Favorites list found

01:52:02
[INFO] 2020-01-29T01:52:02.874Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Getting youtube-dl url for https://www.youtube.com/watch?v=9bZkp7q19f0

01:52:03
[youtube] 9bZkp7q19f0: Downloading webpage

01:52:04
[youtube] 9bZkp7q19f0: Downloading video info webpage

01:52:05
[youtube] 9bZkp7q19f0: Downloading js player vfl7lL1_p

01:52:05
ERROR: Signature extraction failed: Traceback (most recent call last):

01:52:05
File "/var/task/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature

01:52:05
video_id, player_url, s

01:52:05
File "/var/task/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function

01:52:05
cache_res = res(test_string)

01:52:05
File "/var/task/youtube_dl/extractor/youtube.py", line 1356, in <lambda>

01:52:05
return lambda s: initial_function([s])

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 258, in resf

01:52:05
res, abort = self.interpret_statement(stmt, local_vars)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:05
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 92, in interpret_expression

01:52:05
m.group('expr'), local_vars, allow_recursion - 1)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 189, in interpret_expression

01:52:05
m.group('x'), local_vars, allow_recursion - 1)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:05
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 189, in interpret_expression

01:52:05
m.group('x'), local_vars, allow_recursion - 1)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:05
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:05
File "/var/task/youtube_dl/jsinterp.py", line 211, in interpret_expression

01:52:05
raise ExtractorError('Unsupported JS expression %r' % expr)

01:52:05
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

01:52:05
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest

01:52:05
[INFO] 2020-01-29T01:52:05.597Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 youtube_dl error

01:52:05
[INFO] 2020-01-29T01:52:05.597Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 trying pytube

01:52:05
[INFO] 2020-01-29T01:52:05.638Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Getting pytube url for https://www.youtube.com/watch?v=9bZkp7q19f0

01:52:07
[INFO] 2020-01-29T01:52:07.276Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Unable to get URL for 9bZkp7q19f0

01:52:07
[INFO] 2020-01-29T01:52:07.276Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Getting youtube-dl url for https://www.youtube.com/watch?v=CH1XGdu-hzQ

01:52:07
[youtube] CH1XGdu-hzQ: Downloading webpage

01:52:07
[youtube] CH1XGdu-hzQ: Downloading video info webpage

01:52:08
[youtube] CH1XGdu-hzQ: Downloading js player vfl7lL1_p

01:52:09
ERROR: Signature extraction failed: Traceback (most recent call last):

01:52:09
File "/var/task/youtube_dl/extractor/youtube.py", line 1380, in _decrypt_signature

01:52:09
video_id, player_url, s

01:52:09
File "/var/task/youtube_dl/extractor/youtube.py", line 1293, in _extract_signature_function

01:52:09
cache_res = res(test_string)

01:52:09
File "/var/task/youtube_dl/extractor/youtube.py", line 1356, in <lambda>

01:52:09
return lambda s: initial_function([s])

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 258, in resf

01:52:09
res, abort = self.interpret_statement(stmt, local_vars)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:09
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 92, in interpret_expression

01:52:09
m.group('expr'), local_vars, allow_recursion - 1)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 189, in interpret_expression

01:52:09
m.group('x'), local_vars, allow_recursion - 1)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:09
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 189, in interpret_expression

01:52:09
m.group('x'), local_vars, allow_recursion - 1)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 56, in interpret_statement

01:52:09
v = self.interpret_expression(expr, local_vars, allow_recursion)

01:52:09
File "/var/task/youtube_dl/jsinterp.py", line 211, in interpret_expression

01:52:09
raise ExtractorError('Unsupported JS expression %r' % expr)

01:52:09
ExtractorError: Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

01:52:09
(caused by ExtractorError(u"Unsupported JS expression u'[function(c,d){d=(d'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest

01:52:09
[INFO] 2020-01-29T01:52:09.317Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 youtube_dl error

01:52:09
[INFO] 2020-01-29T01:52:09.317Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 trying pytube

01:52:09
[INFO] 2020-01-29T01:52:09.317Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Getting pytube url for https://www.youtube.com/watch?v=CH1XGdu-hzQ

01:52:10
[INFO] 2020-01-29T01:52:10.535Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Unable to get URL for CH1XGdu-hzQ

01:52:10
[INFO] 2020-01-29T01:52:10.536Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Getting youtube-dl url for https://www.youtube.com/watch?v=CVxMTl6cUSE

01:52:10
[youtube] CVxMTl6cUSE: Downloading webpage

01:52:11
[youtube] CVxMTl6cUSE: Downloading video info webpage

01:52:11
END RequestId: 017cc567-68e7-4dc5-a16a-3ad0faacb665

01:52:11
REPORT RequestId: 017cc567-68e7-4dc5-a16a-3ad0faacb665 Duration: 10010.19 ms Billed Duration: 10000 ms Memory Size: 512 MB Max Memory Used: 91 MB Init Duration: 232.01 ms

01:52:11
2020-01-29T01:52:11.575Z 017cc567-68e7-4dc5-a16a-3ad0faacb665 Task timed out after 10.01 seconds

01:52:12
/var/task/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning

01:52:12
warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

01:52:12
START RequestId: 08c94fd8-21eb-42a4-aeaa-b645ff5b609a Version: $LATEST

01:52:12
[INFO] 2020-01-29T01:52:12.15Z 08c94fd8-21eb-42a4-aeaa-b645ff5b609a on_session_ended

01:52:12
END RequestId: 08c94fd8-21eb-42a4-aeaa-b645ff5b609a

01:52:12
REPORT RequestId: 08c94fd8-21eb-42a4-aeaa-b645ff5b609a Duration: 0.39 ms Billed Duration: 100 ms Memory Size: 512 MB Max Memory Used: 27

**Comment by ndg63276** [comment]
Due to some issues, this code is now behind a paywall. But I can tell you, you need to upgrade youtube_dl to the latest version.

**Comment by BopItFreak** [comment]
Thanks, that worked. FYI this works on Echo Auto.

**Comment by Juand201** [comment]
Hi @BopItFreak im very new to aws im using lambda with alexa using youtube_dl yoou know how can i update youtube_dl in lambda? its possible? using aws cli? im a bit related with linux and ssh but not with aws and specifically with lambda.

**Comment by BopItFreak** [comment]
Just replace the youtube_dl folder with the new version in the lambda_function.zip file. The re-upload it to aws.

**Comment by Juand201** [comment]
thanks a lot :) its working again :)))
